all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/task-app.pem

  children:
    frontend:
      hosts:
        frontend-dev:
          ansible_host: 52.213.35.30
    
    backend: 
      hosts:
        backend-dev:
          ansible_host: 18.201.228.255
